### ISSUE TITLE
Issue in main_test.py

### ISSUE THREAD

**Issue by Abhinav-974** [SorourMo/Cloud-Net#9]
I wanted to run direct evaluation with main_test.py if thats possible, since I wanted to adapt the code to run on a custom dataset for later. But im getting the following error on main_test.py -->
Traceback (most recent call last):
  File "/isro_data/Cloud-Net-A-semantic-segmentation-CNN-for-cloud-detection/Cloud-Net/main_test.py", line 64, in <module>
    prediction()
  File "/isro_data/Cloud-Net-A-semantic-segmentation-CNN-for-cloud-detection/Cloud-Net/main_test.py", line 25, in prediction
    imgs_mask_test = model.predict_generator(
AttributeError: 'Functional' object has no attribute 'predict_generator'. Did you mean: 'predict_on_batch'?
 and if i change the function name as suggested (and then remove the argument keywords generator= and steps= since that gave error), I get error as - TypeError: TensorFlowTrainer.predict_on_batch() takes 2 positional arguments but 3 were given

**Comment by drkh-n** [comment]
Hello, you are probably running on old Tensorflow. Since TF 2.X predict_generator() was deprecated. Use model.predict() instead.

**Comment by arrangedcupid0** [comment]
Can confirm, switching to model.predict() worked for me. I was updating legacy code from Keras 2 to Keras 3.
